//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoleWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cour()
        {
            this.inscriptioncours = new HashSet<inscriptioncour>();
        }
    
        public int idcour { get; set; }
        public string nom { get; set; }
        public Nullable<int> idProfesseur { get; set; }
        public int dureeTotale { get; set; }
        public int dureeParJour { get; set; }
        public double prix { get; set; }
        public string jour { get; set; }
        public string heures { get; set; }
        public System.DateTime dateLimite { get; set; }
        public int nbInscriptionMin { get; set; }
        public int nbInscriptionMax { get; set; }
        public System.DateTime dateDebut { get; set; }
        public System.DateTime dateFin { get; set; }
        public string etatcour { get; set; }
    
        public virtual professeur professeur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inscriptioncour> inscriptioncours { get; set; }
    }
}
