//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoleWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class disponibilite
    {
        public int idDisponibilite { get; set; }
        public Nullable<int> idProfesseur { get; set; }
        public bool lundi { get; set; }
        public bool mardi { get; set; }
        public bool mercredi { get; set; }
        public bool jeudi { get; set; }
        public bool vendredi { get; set; }
        public bool samedi { get; set; }
        public bool dimanche { get; set; }
    
        public virtual professeur professeur { get; set; }
    }
}
