//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoleWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ecoleEntities : DbContext
    {
        public ecoleEntities()
            : base("name=ecoleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<cour> cours { get; set; }
        public virtual DbSet<disponibilite> disponibilites { get; set; }
        public virtual DbSet<etudiant> etudiants { get; set; }
        public virtual DbSet<inscriptioncour> inscriptioncours { get; set; }
        public virtual DbSet<professeur> professeurs { get; set; }
    }
}
