//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoleWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inscriptioncour
    {
        public int idInscription { get; set; }
        public Nullable<int> idcour { get; set; }
        public Nullable<int> idEtudiant { get; set; }
        public System.DateTime dateInscription { get; set; }
        public double paiments { get; set; }
    
        public virtual cour cour { get; set; }
        public virtual etudiant etudiant { get; set; }
    }
}
